
before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/voxl-sdk/ci-tools

include:
  - project: 'voxl-public/voxl-sdk/ci-tools'
    file: '/pipeline-configs/qrb5165-emulator.yml'

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build_qrb5165_emulator_dev
    - nightly_qrb5165_emulator_dev
    - deploy_qrb5165_emulator_dev
    - build_qrb5165_emulator_stable
    - nightly_qrb5165_emulator_stable
    - deploy_qrb5165_emulator_stable
