#!/bin/bash

################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
################################################################################

systemctl daemon-reload

echo ""
echo "Done installing rb5-camera-server"
echo ""
echo "Please run rb5-configure-cameras"
echo ""
