#!/bin/bash

################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
################################################################################

systemctl daemon-reload

if [ ! -f /etc/modalai/voxl-camera-server.conf ]; then

    camera-server-config-helper

fi
